language: python
python:
  - "3.8"

services:
  - docker

before_script: pip install docker-compose

jobs:
  include:
    - stage: test
    script: 
    	- docker-compose exec movies flake8
    	- docker-compose exec movies black --exclude=migrations --exclude=env .
    	- docker-compose exec movies pytest -p no:warnings --cov=.
